### ISSUE TITLE
cnpm install或者npm install安装不了W包

### ISSUE THREAD

**Issue by Yakumo-Yukari** [WhiteBlue/bilibili-html5#11]
cnpm:
× Install fail! Error: [w@^2.0.13] GET https://registry.npm.taobao.org/w/%3E%3D2.0.13%20%3C3.0.0 response 404 status
Error: [w@^2.0.13] GET https://registry.npm.taobao.org/w/%3E%3D2.0.13%20%3C3.0.0 response 404 status

npm:
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "D:\\DevTools\\nodejs\\node.exe" "D:\\DevTools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: w@^2.0.13
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.0.1
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget

**Comment by WhiteBlue** [comment]
已修复，```package.json``之前提交的有点问题.....
